### ISSUE TITLE
Content assets not loaded correctly when the H5P player page has a nested URL structure

### ISSUE THREAD

**Issue by mimidotsuser** [tunapanda/h5p-standalone#61]
### Describe the user story:
 As a user, I should be able to override the path to the H5P `content` folder.
Currently, if the player is placed inside a nested URL path e.g. `https://mysite.com/sample/h5p-player.html`, the path retrieving the local content assets such as images and videos does not work.

### Tasks (where applicable)
- [ ]  If the H5P location is a relative path, the content path should always start site origin (exclude any pathname).
- [ ] Allows users to be able to override the H5P content path
- [ ] Add instructions for those without advance coding knowledge who wish to use the library out-of-box #39 #45 
- [ ] Update JQuery dependency #48
- [ ] Bump the package version
